
<div class="box-body">
    <div class="row"> 
              <div class="col-md-6">
              <!-- USERS LIST -->
              <div class="">
                <div class="box-header with-border">
                  <h3 class="box-title">Gravaçao Direita</h3>

                  <div class="box-tools pull-right">
                    
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                    </button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body no-padding">
            
                      
                
                    <video controls="" > </video> 
              
                  
                </div>
                <!-- /.box-body -->
                <div class="box-footer text-center">
                  <a href="javascript:void(0)" class="uppercase"> gravaçao online...</a>
                </div>
                <!-- /.box-footer -->
              </div>
              <!--/.box -->
            </div>
               
                
            </div>
  </div>
<?php
