

<div class="tab-pane" id="settings">
    <form class="form-horizontal" method="post" action="salvar_registo_video" enctype="multipart/form-data">
                  
                  <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">Titulo</label>

                    <div class="col-sm-6"> 
                        <input type="text" class="form-control" name="titulo"  placeholder="Titulo do Video"/>
                    </div>
                  </div>
                      <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">Curso</label>

                    <div class="col-sm-6"> 
                        <input type="text" class="form-control" name="curso" placeholder="Curso pertecente"/>
                    </div>
                  </div>
                  <div class="form-group">
                      <label for="inputName" class="col-sm-2 control-label">Descri&ccedil;&atilde;o</label>

                    <div class="col-sm-6">
                        <input type="text" class="form-control" name="descricao"  placeholder="Descrição"/>
                    </div>
                  </div>
                      
                  <div class="form-group ">
               
              <label for=inputFile" class="col-sm-2 control-label">Arquivo</label>   
              <div class="col-sm-6">
               
              <input type="file" name="arquivo"  class="form-control"/>
         
             </div>
            </div>
                  
                  <div class="form-group">
                    
                      
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </div>
                </form>
              </div>



<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

