
<div class="login-box">
    <div class="login-logo">
      <a href=""><b>Login ou Cadastra-se</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body ">
      <p class="login-box-msg">iniciar sessão</p>
      
      <form action="validar" method="POST">
        <div class="form-group has-feedback">
            <input type="text" class="form-control" name="email" placeholder="Email" required>
          <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
            <input type="password" class="form-control" name="senha"placeholder="Password" required>
          <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <div class="row">
          <div class="col-xs-8">
            <div class="checkbox icheck">
              <label>
                <input type="checkbox"> lembrar Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
      
      <div class="social-auth-links text-center">
        <p>- OU -</p>
        <a href="<?php echo APP_LOGIN;?>cadastrar_usuario" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i>  
           Cadastra-se </a>
         
          </div>
          <!-- /.social-auth-links -->
          
          <a href="#">Esqueceu a password</a><br>
          
          
        </div>
        <!-- /.login-box-body -->
      </div>
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

