
<h3>
    confirma a exclusão dos dados
    
    
</h3>

<p> Nome:<?php echo $view_dados->nome;?> </p>
<a href="admin/usuario/confirmaDeletar/<?php echo $view_dados->codgusario;?>/<?php echo $view_dados->nome;?>"> Deseja eleiminar</a>

<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

