
<?php  $pessoa =$_SESSION['unia'];?>
  <!-- Content Wrapper. Contains page content -->
  <div >
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Perfil do Usuario
      </h1>
      
    </section>

    <!-- Main content -->
    <section class="content">

      <div class="row">
        <div class="col-md-3">
         
          <!-- Profile Image -->
          <div class="box box-primary">
            <div class="box-body box-profile">
                
              <img class="profile-user-img img-responsive img-circle" src="<?php 
                if(!empty($_SESSION['unia']->foto)){
                  
                  echo  ("././../../fotos/").$_SESSION['unia']->foto ;
                 
                }else {
                         
                    echo  ("././../../fotos/perfil.jpg") ;
                    
                } ?>" alt="User profile picture">

              <h3 class="profile-username text-center"><?php echo ''.$pessoa ->nome;?></h3>

              <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">sobre Me</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <strong><i class="fa fa-book margin-r-5"></i> Universidade</strong>

              <p class="text-muted">
                <?php echo (isset($view_dados->universidade) ? $view_dados->universidade : 'UNIA - Universidade independente' );?>
              </p>

              <hr>

              <strong><i class="fa fa-map-marker margin-r-5"></i> Morada</strong>

              <p class="text-muted"> <?php echo (isset($view_dados->morada) ? $view_dados->morada : 'Municipio de Belas, Murro Bento I, Rua 21 de Janeiro,  ' ); ?>
              </p>
              <hr>

              <strong><i class="fa fa-file-text-o margin-r-5"></i> Cursos</strong>

              <p> <?php echo (isset($view_dados->curso) ? $view_dados->curso : 'Ciencia Universal ' ); ?> </p>
              
            </div>
            
            <a  href="sobre_me" class="btn btn-danger btn-primary">Editar Informação</a>
          </div>
              <p>
                  
                  
              </p>   
          
            </div>
            <!-- /.box-body -->
          </div>
          
        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              
              <li  class="active"><a href="#timeline" data-toggle="tab">Estado Pessoal</a></li>
              <li><a href="#settings" data-toggle="tab">Alterar Palavra Passe</a></li>
            </ul>
              
            <div class="tab-content">
            
              <!-- /.tab-pane -->
              <div class="active tab-pane" id="timeline">
                <!-- The timeline -->
                <ul class="timeline timeline-inverse">
                  <!-- timeline time label -->
                  <li class="time-label">
                        <span class="bg-red">
                          <?php echo 'Data da criação- 2017';?>
                        </span>
                  </li>
                  <!-- /.timeline-label -->
                  <!-- timeline item -->
                  <li>
                    <i class="fa fa-envelope bg-blue"></i>

                    <div class="timeline-item">
                      <span class="time"><i class="fa fa-clock-o"></i> </span>

                      <h3 class="timeline-header"><a href="#">Dados Pessoas:</a> </h3>

                      <div class="timeline-body">
                        Nome Completo:  <strong> <?php echo ' '.$pessoa ->nome;?> </strong>
                        <p> 
                          SobreNome:  <strong><?php echo ' '.$pessoa ->apelido;?></strong>
                         </p>
                          Telefone:  <strong><?php echo ' '.$pessoa ->telefone;?></strong>
                          <p> 
                           Numero de Estudante:  <strong><?php echo ' '.$pessoa ->numeroEstudante;?></strong>
                          </p>
                       </div>
                      <div class="timeline-footer">
                        <!--<a class="btn btn-primary btn-xs">Read more</a>-->
                        <a class="btn btn-danger btn-primary">Editar</a>
                      </div>
                    </div>
                  </li>
                  <!-- END timeline item -->
                  <!-- timeline item -->
                  <li>
                    <i class="fa fa-user bg-aqua"></i>

                    <div class="timeline-item">
                      <span class="time"><i class="fa fa-clock-o"></i> 5 mins ago</span>

                      <h3 class="timeline-header border"><a href="#">Dados da conta:</a> 
                      </h3>
                      <div class="timeline-body">
                        Email:<strong> <?php  echo ' '.$pessoa ->email;?> </strong>
                        <p> 
                         Categoria: <strong>
                             <?php 
                             if($pessoa ->nivel == 3){
                               echo 'Administrador';
                               }
                            elseif ($pessoa ->nivel == 3) {
                             echo 'Docente';
                            }
                             elseif ($pessoa ->nivel == 1) {
                                  echo 'Estudante';
                            }
                        ?> </strong>
                         </p>
                         
                       </div>
                    </div>
                  </li>
                  <!-- END timeline item -->
                  <!-- timeline item -->
<!--                  <li>
                    <i class="fa fa-comments bg-yellow"></i>

                    <div class="timeline-item">
                      <span class="time"><i class="fa fa-clock-o"></i> 27 mins ago</span>

                      <h3 class="timeline-header"><a href="#">Linha de Tempo: </a> Frase  do Dia</h3>

                      <div class="timeline-body">
                        <div class="post clearfix">

                  <p>
                      <?php echo 'A diferença entre o sonhador e o realizador é que o
                                  segundo faz acontecer. A realização é a concretização.
                                O sonho é apenas matéria-prima. Um sonho deve
                                  impelir ao movimento, nunca à estagnação'; ?>
                  </p>
               <ul class="list-inline">
                    <li><a href="#" class="link-black text-sm"><i class="fa fa-share margin-r-5"></i> Partilhar</a></li>
                    <li><a href="#" class="link-black text-sm"><i class="fa fa-thumbs-o-up margin-r-5"></i> Like</a>
                    </li>
                    <li class="pull-right">
                      <a href="#" class="link-black text-sm"><i class="fa fa-comments-o margin-r-5"></i> Co</a></li>
                     
                  </ul>
                  <form class="form-horizontal">
                    <div class="form-group margin-bottom-none">
                      <div class="col-sm-9">
                          <input class="form-control input-sm"  name="frase" placeholder="Response">
                      </div>
                      <div class="col-sm-3">
                        <button type="submit" class="btn btn-primary pull-right btn-block btn-sm">Send</button>
                      </div>
                    </div>
                  </form>
                </div>
                      </div>
                      <div class="timeline-footer">
                        <a class="btn btn-warning btn-flat btn-xs">####</a>
                      </div>
                    </div>
                  </li>-->
                  
                  <li>
                       <i class="fa fa-clock-o bg-yellow"></i>
                      <div class="timeline-item">  
                       
                          <div class="timeline-footer">
                             <a href="#" class="btn btn-danger btn-sm"><b>Desativar a Conta</b></a>  
                          </div>
                       
                      </div>
                   
                  </li>
                </ul>
              </div>
              <!-- /.tab-pane -->

              <div class="tab-pane" id="settings">
                  <form class="form-horizontal" method="POST" action="alterar_senha">
                  <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">Antiga Senha</label>

                    <div class="col-sm-6">
                        <input type="password" class="form-control" name="senha_antiga1" id="inputName" placeholder="Senha Antiga">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">Nova Senha</label>

                    <div class="col-sm-6"> 
                      <input type="password" class="form-control" name="senha_nova1" id="inputEmail" placeholder="senha Nova">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">Confirma Novamente</label>

                    <div class="col-sm-6">
                      <input type="password" class="form-control" name="senha" id="inputName" placeholder="senha Nova">
                    </div>
                  </div>
                  
                  
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <div class="checkbox">
                        <label>
                          <input type="checkbox"> aceita o termo<a href="#"></a>
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-danger">Submit</button>
                    </div>
                  </div>
                </form>
              </div>
              <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
          </div>
          <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
 

  <!-- Control Sidebar -->
  
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

<!--</body>-->