

<form action="salva" method="post">
   
    <P> <input type="hidden" name="codgusario" value="<?php echo isset($view_dados->codgusario) ; ?>"> </P>
    <P>nome <input type="text" name="nome" value="<?php echo isset($view_dados->nome); ?>"> </P>
    <P> usuario<input type="text" name="email" value="<?php echo isset($view_dados->email); ?>"> </P>
    <P> senha<input type="text" name="senha" value="<?php echo isset($view_dados->senha); ?>"> </P>
       <button type="submit"> Gravar </button> 
      
</form>  


<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

