

<div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <?php if(count($view_listUsuario) > 0):?>
                <tr>
                  <th>Nome</th>
                  <th>Apelido</th>
                  <th>Telefone</th>
                  <th>Numero de Estudante</th>
                  <th>Nivel</th>
                  <th>Email</th>
                  <th>Detalhe</th>
                    <th>Actualizar</th>
                      <th>Eliminar</th>
                </tr>
                </thead>
                <tbody>
          
           <?php foreach ($view_listUsuario as $li):  ?>
            
       
                <tr>
                    <td> <?php echo $li->nome ;?></td>
                  <td>  <?php echo $li->apelido ;?></td>
                  <td> <?php echo $li->telefone ;?></td>
                  <td>  <?php echo $li->numeroEstudante ;?></td>
                  <td> <?php echo $li->nivel ;?></td>
                  <td> <?php echo $li->email ;?> </td>
                  
                  <td> <a href="<?php echo APP_ADMIN;?>usuario/informacao/<?php echo $li->codgusario; ?>" class="btn btn-block btn-primary"> Informa&ccedil;&atilde;o</a> </td>
                    <td> <a href="<?php echo APP_ADMIN;?>usuario/cadastrar_usuario/<?php echo $li->codgusario; ?>" class="btn btn-block btn-success">Actualizar</a></td>
                   <td> <a href="<?php echo APP_ADMIN;?>usuario/eliminar_usuario/<?php echo $li->codgusario; ?>" class="btn btn-block btn-danger">Eliminar</a></td>

                </tr>
        <?php endforeach; ?>
         <?php else: ?>
          
             
               <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i> Alerta...!</h4>
                <?php echo "Não tem nenhum usuario cadastrado"; ?>
              </div> 
              
              
        <?php  endif; ?>
                </tbody>

              </table>
            </div>

<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

