
 <!-- a QUE É ONDE VAI SER DADA A RESPOSTA QUANDO HAVER SUCESSO DO CADASTRO -->
<div >
          <div class="box box-default">
            <div class="box-header with-border">
            
            </div>
            <!-- /.box-header -->
            <?php 
           
               if(count($view_salvar) > 0){ ?>
            <div class="box-body">
                
                 <?php  if($view_salvar["sucess"]==TRUE) {?>
              <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i> Alert! ..  <?php echo $view_salvar["feedback"]; ?></h4>
              
              </div>
                <?php  } ?>

                
                <?php  if(!$view_salvar["sucess"]) {?>
              <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-ban"></i> Alert!..  <?php echo $view_salvar["feedback"]; ?></h4>
                 
              </div>
                <?php }?>

            </div>
            
            <?php  }?>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
