<!DOCTYPE html>
<html lang="en">

<head>
 <!-- princippal  layout da aplicação quando executar-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $this->title; ?></title>
    
    <link rel="stylesheet" href="./../../content/Publica/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="./../../content/Publica/assets/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="./../../content/Publica/assets/css/animate.css">
    <link rel="stylesheet" href="./../../content/Publica/assets/css/magnific-popup.css">
    <link rel="stylesheet" href="./../../content/Publica/assets/flexslider/flexslider.css">
    <link rel="stylesheet" href="./../../content/Publica/assets/css/form-elements.css">
    <link rel="stylesheet" href="./../../content/Publica/assets/css/style.css">
    <link rel="stylesheet" href="./../../content/Publica/assets/css/media-queries.css">
 

     <!-- Favicon and touch icons -->
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="./../../content/Publica/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="./././content/Publica/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="./../../Publica/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="./../../content/Publica/assets/ico/apple-touch-icon-57-precomposed.png">

<base href="<?php echo APP_ROOT;?>">
</head>

<body>
    <br>
    
    <?php 
     /**
      *   AQUE É ONDE ESTA SER RENDERIZADO O INDEX PRINCIPAL QUE ESTA NA VIEW, E OUTROS FORMULARIOS 
      */
     $this->render(); 
     
     
     
     ?>
     <!-- Javascript -->
     <script src="./../../content/Publica/assets/js/jquery-1.11.1.min.js"></script>
    <script src="./../../content/Publica/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="../../content/Publica/assets/js/bootstrap-hover-dropdown.min.js"></script>
    <script src="./../../content/Publica/assets/js/jquery.backstretch.min.js"></script>
    <script src="../../content/Publica/assets/js/wow.min.js"></script>
    <script src="./../../content/Publica/assets/js/retina-1.1.0.min.js"></script>
    <script src="../../content/Publica/assets/js/jquery.magnific-popup.min.js"></script>
    <script src="./../../content/Publica/assets/flexslider/jquery.flexslider-min.js"></script>
    <script src="../../content/Publica/assets/js/jflickrfeed.min.js"></script>
    <script src="../../content/Publica/assets/js/masonry.pkgd.min.js"></script>
     <!--    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>-->
    <script src="../../../content/Publica/assets/js/jquery.ui.map.min.js"></script>
    <script src="./../../content/Publica/assets/js/scripts.js"></script>
    
</body>
</html>