
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="././../../fotos/logo.ico">
    <title><?php echo $this->title; ?></title>

 
    <base href="<?php echo APP_ROOT;?>">
</head>

<body>
    <!--   layout do login do usario-->
    <?php echo 'usuario sem acesso';?>
    <?php $this->render(); ?>
    
    
</body>
</htm


<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

