<div class="">
<!--    <section class="content ">  register-box-->
<div class="row">
   
         <div >
        <div class="box-header with-border">
          <h3 class="box-title">Registar Pagamento</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
           <form role="form" action="salvar_Pagamento" method="POST" enctype="multipart/form-data">
          <div class="box-body">

              
         <div class="form-group has-feedback col-sm-6">
             <label for="exampleInputName">Numero de Estudante</label>
             
           <input type="text" class="form-control"  name="numeroEstudante" value="<?php echo isset($view_dados->numeroEstudantee) ? $view_dados->numeroEstudante:''; ?>"placeholder="Numero de Estudante" required>
                <span class="glyphicon glyphicon-check form-control-feedback"></span>
             </div>
           
            
           <div class="form-group has-feedback col-sm-6">
              <label for="exampleInputEmail1">Email</label>
              <input type="email" class="form-control" id="exampleInputEmail1" name="email"value="<?php echo isset($view_dados->email) ? $view_dados->email:''; ?>" placeholder="Email" required>
              <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
              <div class="form-group has-feedback col-sm-6">
                  <label for="exampleInputEmail1">Mes</label>
                  <input type="text" class="form-control" name="mes" placeholder="Mes" required>
            <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
          
              </div>

              <div class="form-group has-feedback col-sm-6">
                  <label for="exampleInputEmail1">Numero de Ordem do Borderom</label>
            <input type="text" class="form-control" name="borderom" value="<?php echo isset($view_dados->borderom) ? $view_dados->borderom :''; ?>" placeholder="numero do borderom" required>
             <span class="glyphicon glyphicon-user form-control-feedback"></span>
              </div>
        
             <div class="form-group has-feedback col-sm-6">
             <label for="exampleInputName">Quantos Meses</label>
             
           <input type="text" class="form-control"  name="numero_de_meses" value="<?php echo isset($view_dados->numero_de_meses) ? $view_dados->numero_de_meses:''; ?>"placeholder="meses a pagar" required>
                <span class="glyphicon glyphicon-check form-control-feedback"></span>
             </div>  
              
               <div class="form-group has-feedback col-sm-6">
             <label for="exampleInputName">Valor pago</label>
             
           <input type="text" class="form-control"  name="valorPago" value="<?php echo isset($view_dados->valorPago) ? $view_dados->valorPago:''; ?>"placeholder="valor pago" required>
                <span class="glyphicon glyphicon-check form-control-feedback"></span>
             </div>
              
            <div class="checkbox form-group col-sm-6">
              <label>
                <input type="checkbox"> Aceita
              </label>
            </div>
          </div>
          <!-- /.box-body -->

          <div class="form-group col-sm-6"> 
            <button type="submit" class="btn btn-primary">Salvar</button>
          </div>
        </form>
      </div>

  
</div>
<!-- </section>       -->
</div>


<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

