

<div class="tab-pane" id="settings">
    <form class="form-horizontal" method="post" action="salvar_cadastrar" enctype="multipart/form-data">
                  
                  <div class="form-group">
                    <label for="" class="col-sm-2 control-label">Nome do Arquivo</label>

                    <div class="col-sm-6"> 
                        <input type="text" class="form-control" name="nome"  placeholder="Nome do Arquivo" required/>
                    </div>
                  </div>
                      <div class="form-group">
                    <label for="" class="col-sm-2 control-label"> Area de Formação</label>

                    <div class="col-sm-6"> 
                        <input type="text" class="form-control" name="area_formacao" placeholder="Area de Formação" required/>
                    </div>
                  </div>
                  <div class="form-group">
                      <label for="inputName" class="col-sm-2 control-label">Descri&ccedil;&atilde;o</label>

                    <div class="col-sm-6">
                        <input type="text" class="form-control" name="descricao"  placeholder="Descrição" required/>
                    </div>
                  </div>
                      
                  <div class="form-group ">
               
              <label for=inputFile" class="col-sm-2 control-label">Arquivo</label>   
              <div class="col-sm-6">
               
                  <input type="file" name="ficheiro"  class="form-control" required/>
         
             </div>
            </div>
                  
                  <div class="form-group">
                    
                      
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                  </div>
                </form>
              </div>



<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

