
<div >
    <div class="box box-default"> 
            <div class="box-header with-border">
            
            </div>
            <!-- /.box-header -->
            <?php 
               if(isset($view_resposta)){ ?>
            <div class="box-body">
                
                 <?php  if($view_resposta['sucess']==TRUE) {?>
              <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i> Alert!</h4>
                <?php echo $view_resposta['feedback'].' no cadastro do Ficheiro'; ?>
              </div>
                <?php  } ?>

                
                <?php  if(!$view_resposta['sucess']) {?>
              <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                  <?php echo '  ERRO NÃO FOI FAZER O CADSTRAMENTO O FICHEIRO'; ?>
              </div>
                <?php }?>

            </div>
            
            <?php  }?>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
