  
   <!-- Top menu -->
		<nav class="navbar" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="">Andia - a super cool design agency...</a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="top-navbar-1">
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="<?php echo APP_SITE_HOME;?>index"   data-delay="1000">
								<i class="fa fa-home"></i><br>Home 
							</a>
<!--							<ul class="dropdown-menu dropdown-menu-left" role="menu">
								<li><a href="index.html">Home</a></li>
								<li><a href="index-2.html">Home 2</a></li>
							</ul>-->
						</li>
                                                  <li>
                                                    <a href="<?php echo APP_SITE_HOME;?>universidade"><i class="fa fa-tasks"></i><br>Universidade</a>
                                                  </li>
                                                
						<li >
							<a href="<?php echo APP_SITE_HOME;?>servico"><i class="fa fa-camera"></i><br>Serviço</a>
						</li>
						<li class="active">
							<a href="<?php echo APP_SITE_HOME;?>cursos"><i class="fa fa-tasks"></i><br>Cursos</a>
						</li>
						<li>
							<a href="<?php echo APP_SITE_HOME;?>quemSomos"><i class="fa fa-user"></i><br>Quem Somos</a>
						</li>
						
						<li class="dropdown">
							<a href="<?php echo APP_LOGIN;?>login"  data-hover="dropdown" data-delay="1000">
								<i class="fa fa-paperclip"></i><br>Login 
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

        <!-- Page Title -->
        <div class="page-title-container">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 wow fadeIn">
                        <i class="fa fa-tasks"></i>
                        <h1>Cursos Lecionados/</h1>
                        <p>O Conhecimento do Saber........</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Services Full Width Text -->
        <div class="services-full-width-container">
        	<div class="container">
	            <div class="row">
	                <div class="col-sm-12 services-full-width-text wow fadeInLeft">
	                    <h3>Nota Informativa</h3>
	                    <p>
	                    	A Universidade Independente de Angola nasceu de um sonho e representa o esforço e o entusiasmo de um grupo de angolanos dispostos a dar o seu contributo para o desenvolvimento e consolidação da Educação e do Saber em Angola. <strong>eiusmod tempor</strong> incididunt.
	                	O número de discentes matriculados em 2004 não ultrapassava os 855. E as infra-estruturas também não eram suficientes. Há quatro anos atrás iniciou-se com apenas duas salas de aulas com capacidade para 50 alunos cada
                            
                            </p>
	                </div>
	            </div>
	        </div>
        </div>

        <!-- Services -->
        <div class="work-container">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 work-title wow fadeIn">
                    <h2>Cursos de Engenharia </h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <div class="work wow fadeInUp">
                      <!--  <img src="././Publica/assets/img/portfolio/work1.jpg" alt="Lorem Website" data-at2x="assets/img/portfolio/work1.jpg">-->
                        <h3>Arquitectura e Urbanismo</h3>
                        <p>Os diplomados em Arquitectura e Urbanismo serão responsáveis pela integração harmoniosa das actividades humanas no território, valorizando o património construído e o ambiente. </p>
                        <div class="work-bottom">
                            <a class="big-link-2 view-work" href="././Publica/assets/img/portfolio/work1.jpg"><i class="fa fa-search"></i></a>
                            <a class="big-link-2" href="portfolio.html"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInDown">
                       <!-- <img src="././Publica/assets/img/portfolio/work2.jpg" alt="Ipsum Logo" data-at2x="assets/img/portfolio/work2.jpg">-->
                        <h3>Invesão</h3>
                        <p>O objectivo da licenciatura em Ciências da Comunicação é o de dotar os nossos licenciados de instrumentos técnicos e científicos que lhes permitam o exercício...</p>
                        <div class="work-bottom">
                            <a class="big-link-2 view-work" href="assets/img/portfolio/work2.jpg"><i class="fa fa-search"></i></a>
                            <a class="big-link-2" href="portfolio.html"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInUp">
                       <!-- <img src="././Publica/assets/img/portfolio/work3.jpg" alt="Dolor Prints" data-at2x="assets/img/portfolio/work3.jpg">-->
                        <h3>Engenharia Civil</h3>
                        <p>O ensino é um dos alicerces mais importantes um desenvolvimento sócio-económico sustentável de cada nação. Pelo que é indiscutível a importância da educação.....</p>
                        <div class="work-bottom">
                            <a class="big-link-2 view-work" href="assets/img/portfolio/work3.jpg"><i class="fa fa-search"></i></a>
                            <a class="big-link-2" href="portfolio.html"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInDown">
                        <!--<img src="././Publica/assets/img/portfolio/work4.jpg" alt="Sit Amet Website" data-at2x="assets/img/portfolio/work4.jpg">-->
                        <h3>Informatica</h3>
                        <p>O Engenheiro Informático desenvolverá as suas funções tanto em entidades privadas nacionais ou multinacionais como em Organismos Públicos, quer ao nível nacional quer ao nível provincial ou regional....</p>
                        <div class="work-bottom">
                            <a class="big-link-2 view-work" href="assets/img/portfolio/work4.jpg"><i class="fa fa-search"></i></a>
                            <a class="big-link-2" href="portfolio.html"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        <!-- Services Half Width Text -->
        <div class="work-container">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 work-title wow fadeIn">
                    <h2>Cursos de Adiministração</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <div class="work wow fadeInUp">
                        <!--<img src="././Publica/assets/img/portfolio/work1.jpg" alt="Lorem Website" data-at2x="assets/img/portfolio/work1.jpg">-->
                        <h3>Engenharia dos Recursos Naturais</h3>
                        <p>O licenciado em Engenharia de Recursos Naturais e Ambiente fará parte de equipas associadas à concepção e execução de Projectos de Prospecção e Exploração de recursos, Estudos Ambientais..</p>
                        <div class="work-bottom">
                            <a class="big-link-2 view-work" href="././Publica/assets/img/portfolio/work1.jpg"><i class="fa fa-search"></i></a>
                            <a class="big-link-2" href="portfolio.html"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInDown">
                        <!--<img src="././Publica/assets/img/portfolio/work2.jpg" alt="Ipsum Logo" data-at2x="assets/img/portfolio/work2.jpg">-->
                        <h3>Sociologia </h3>
                        <p>A licenciatura em Sociologia tem por objectivo oferecer aos alunos uma abordagem da disciplina aberta, plural e actualizada, bem como uma aprendizagem que articula a formação teórica e metodológica...</p>
                        <div class="work-bottom">
                            <a class="big-link-2 view-work" href="assets/img/portfolio/work2.jpg"><i class="fa fa-search"></i></a>
                            <a class="big-link-2" href="portfolio.html"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInUp">
                       <!-- <img src="././Publica/assets/img/portfolio/work3.jpg" alt="Dolor Prints" data-at2x="assets/img/portfolio/work3.jpg">-->
                        <h3>Direito</h3>
                        <p>A licenciatura em Direito visa a formação de juristas com uma formação clássica, mas atendendo sempre o estádio de desenvolvimento da sociedade angolana...</p>
                        <div class="work-bottom">
                            <a class="big-link-2 view-work" href="assets/img/portfolio/work3.jpg"><i class="fa fa-search"></i></a>
                            <a class="big-link-2" href="portfolio.html"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInDown">
                       <!-- <img src="././Publica/assets/img/portfolio/work4.jpg" alt="Sit Amet Website" data-at2x="assets/img/portfolio/work4.jpg">-->
                        <h3> Psicologia</h3>
                        <p>O Psicólogo especializado nesta área deverá possuir um determinado conjunto de competências académicas a adquirir durante o 2º ciclo de formação e na prática profissional supervisionada ..</p>
                        <div class="work-bottom">
                            <a class="big-link-2 view-work" href="assets/img/portfolio/work4.jpg"><i class="fa fa-search"></i></a>
                            <a class="big-link-2" href="portfolio.html"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        <!-- Call To Action -->
<!--        <div class="call-to-action-container">
        	<div class="container">
	            <div class="row">
	                <div class="col-sm-12 call-to-action-text wow fadeInLeftBig">
	                    <p>
	                    	Lorem ipsum <span class="violet">dolor sit amet</span>, consectetur adipisicing elit, 
	                    	sed do eiusmod tempor incididunt ut labore et ut wisi.
	                    </p>
	                    <div class="call-to-action-button">
	                        <a class="big-link-3" href="#">Try It Now!</a>
	                    </div>
	                </div>
	            </div>
	        </div>
        </div>-->

        <!-- Footer -->
        <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-3 footer-box wow fadeInUp">
                    <h4>Sobre-nos</h4>
                    <div class="footer-box-text">
                        <p>
                            somos uma empresa de informação a tempo e hora basta.. tudo que vc precisa a que voce encontra
                        </p>
                        <p><a href="about.html">saiba mais...</a></p>
                    </div>
                </div>
                

                <div class="col-sm-3 footer-box wow fadeInDown">
                    <h4>Contato</h4>
                    <div class="footer-box-text footer-box-text-contact">
                        <p><i class="fa fa-map-marker"></i> Address: avenida patriota BºBemvindo</p>
                        <p><i class="fa fa-phone"></i> Phone: 924-18-65-05/990-18-65-05</p>
                        <p><i class="fa fa-user"></i> Skype: Multimidia-web</p>
                        <p><i class="fa fa-envelope"></i> Email: <a href="">multimidia_web@gmail.com</a></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 wow fadeIn">
                    <div class="footer-border"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 footer-copyright wow fadeIn">
                    <p>Copyright 2012-todo direito reservado by <a href="">Multimidia-web</a>.</p>
                </div>
                <div class="col-sm-5 footer-social wow fadeIn">
                    <a href="almeida almeida"><i class="fa fa-facebook"></i></a>

                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-pinterest"></i></a>
                </div>
            </div>
        </div>
    </footer>
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

