  <!-- Top menu -->
    <nav class="navbar" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
                <a class="navbar-brand" href="">Unia... A melhor de tudo</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="top-navbar-1">
                <ul class="nav navbar-nav navbar-right ">
                    <li class="dropdown active">
                        <a href="#"  data-delay="1000">
                            <i class="fa fa-home"></i><br>Home <span class="caret"></span>
                        </a>

                    </li>
                    <li>
                        <a href="<?php echo APP_SITE_HOME;?>universidade"><i class="fa fa-certificate"></i><br>Universidades de Angola</a>
                    </li>
                    <li>
                        <a href="<?php echo APP_SITE_HOME;?>servico"><i class="fa fa-tasks"></i><br>Serviço</a>
                    </li>
                    <li>
                        <a href="<?php echo APP_SITE_HOME;?>cursos"><i class="fa fa-bookmark"></i><br>Cursos</a>
                    </li>
                    <li>
			<a href="<?php echo APP_SITE_HOME;?>quemSomos"><i class="fa fa-user"></i><br>Quem Somos</a>
			</li>
                    
                    <!--                    <li>
                        <a href="contact.html"><i class="fa fa-envelope"></i><br>Contacto</a>
                    </li>-->
                    <li class="dropdown">
                        <a href="<?php echo APP_LOGIN;?>login"  data-hover="dropdown" data-delay="1000">
                            <i class="fa fa-paperclip"></i><br>Login
                        </a>

                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Slider 2 -->
    <div class="slider-2-container">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2 slider-2-text wow fadeInUp">
                    <h1>Nos somos <span class="violet">Unia</span> A que voce encontra o seu sonho</h1>
                    <p>o mundo é uma arte de grandeza </p>
                </div>
            </div>
        </div>
    </div>

    <!-- Services -->
    <div class="services-container">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 services-title wow fadeIn">
                    <h2>Informação </h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <div class="service wow fadeInUp">
                        <div class="service-icon"><i class="fa fa-user"></i></div>
                        <h3>Estudos Academicos</h3>
                        <p> A Universidade Independente de Angola, UnIA – iniciou a sua actividade no dia 02 de Junho de 2004 apenas ministrando aulas do Ano Propedêutico para 4 (quatro) licenciaturas: </p>
                        <a class="big-link-1" href="universidade">Saiba Mais </a>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="service wow fadeInDown">
                        <div class="service-icon"><i class="fa fa-table"></i></div>
                        <h3>Formação</h3>
                        <p>Universidade angolana achou-se por bem arrancar com o Ano Propedêutico por se julgar útil e necessário para moldar os conhecimentos dos alunos que ingressaram no ensino superior</p>
                        <a class="big-link-1" href="servico">Saiba Mais</a>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="service wow fadeInUp">
                        <div class="service-icon"><i class="fa fa-magic"></i></div>
                        <h3>Aulas Gravada & Cursos</h3>
                        <p>.Temos ao vosso dispor um serviço inovador criado pela UnIA que permite aos alunos consultar informações relacionadas com os seus dados pessoais, notas, disciplinas de cada curso, horários e muito mais, tudo pela Internet..</p>
                        <a class="big-link-1" href="cursos">Saiba Mais</a>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="service wow fadeInDown">
                        <div class="service-icon"><i class="fa fa-print"></i></div>
                        <h3>Cadastra-se</h3>
                        <p>Para voce estar dentro dos  Nessa altura como pontos fortes há que salientar o bom entrosamento entre a administração da DEA, a entidade instituidora da UnIA e a Reitora da Universidade...</p>
                        <a class="big-link-1" href="<?php echo APP_LOGIN;?>cadastrar_usuario">Saiba Mais</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Latest work -->
    

    <!-- Testimonials -->
    <div class="testimonials-container">
        <div class="container">

        </div>
    </div>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-3 footer-box wow fadeInUp">
                    <h4>Sobre-nos</h4>
                    <div class="footer-box-text">
                        <p>
                            somos uma empresa de informação a tempo e hora basta.. tudo que vc precisa a que voce encontra
                        </p>
                        <p><a href="quemSomos">saiba mais...</a></p>
                    </div>
                </div>

                <div class="col-sm-3 footer-box wow fadeInDown">
                    <h4>Contato</h4>
                    <div class="footer-box-text footer-box-text-contact">
                        <p><i class="fa fa-map-marker"></i> Address: avenida patriota BºBemvindo</p>
                        <p><i class="fa fa-phone"></i> Phone: 924-18-65-05/990-18-65-05</p>
                        <p><i class="fa fa-user"></i> Skype: Multimidia-web</p>
                        <p><i class="fa fa-envelope"></i> Email: <a href="">multimidia_web@gmail.com</a></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 wow fadeIn">
                    <div class="footer-border"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 footer-copyright wow fadeIn">
                    <p>Copyright 2012-todo direito reservado by <a href="">Multimidia-web</a>.</p>
                </div>
                <div class="col-sm-5 footer-social wow fadeIn">
                    <a href="almeida almeida"><i class="fa fa-facebook"></i></a>

                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-pinterest"></i></a>
                </div>
            </div>
        </div>
    </footer>

   