 <!-- Top menu -->
		<nav class="navbar" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="index.html">Andia - a super cool design agency...</a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="top-navbar-1">
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="<?php echo APP_SITE_HOME;?>index"   data-delay="1000">
								<i class="fa fa-home"></i><br>Home 
							</a>
<!--							<ul class="dropdown-menu dropdown-menu-left" role="menu">
								<li><a href="index.html">Home</a></li>
								<li><a href="index-2.html">Home 2</a></li>
							</ul>-->
						</li>
                                                  <li>
                                                    <a href="<?php echo APP_SITE_HOME;?>universidade"><i class="fa fa-tasks"></i><br>Universidade de Angola</a>
                                                  </li>
                                                
						<li >
							<a href="<?php echo APP_SITE_HOME;?>servico"><i class="fa fa-camera"></i><br>Serviço</a>
						</li>
						<li >
							<a href="<?php echo APP_SITE_HOME;?>cursos"><i class="fa fa-tasks"></i><br>Cursos</a>
						</li>
						<li class="active">
							<a href="<?php echo APP_SITE_HOME;?>quemSomos"><i class="fa fa-user"></i><br>Quem Somos</a>
						</li>
<!--						<li>
							<a href="contact.html"><i class="fa fa-envelope"></i><br>Contacto</a>
						</li>-->
						<li class="dropdown">
							<a href="<?php echo APP_LOGIN;?>login"  data-hover="dropdown" data-delay="1000">
								<i class="fa fa-paperclip"></i><br>Login 
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

        <!-- Page Title -->
        <div class="page-title-container">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 wow fadeIn">
                        <i class="fa fa-user"></i>
                        <h1>Quem Somos/</h1>
                        <p>As nossas maior solução pra o planeta </p>
                    </div>
                </div>
            </div>
        </div>

        <!-- About Us Text -->
        <div class="about-us-container">
        	<div class="container">
	            <div class="row">
	                <div class="col-sm-12 about-us-text wow fadeInLeft">
	                    <h3>A sofil </h3>
	                    <p>
	                    	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. 
	                    	Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper <span class="violet">suscipit lobortis</span> 
	                    	nisl ut aliquip ex ea commodo consequat. Lorem ipsum <strong>dolor sit amet</strong>, consectetur adipisicing elit, 
	                    	sed do eiusmod tempor incididunt ut labore et. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper 
	                    	suscipit lobortis nisl ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, 
	                    	sed do <strong>eiusmod tempor</strong> incididunt.
	                    </p>
	                    
	                    
	                </div>
	            </div>
	        </div>
        </div>

        
        <div class="contact-us-container">
        	<div class="container">
	            <div class="row">
	                <div class="col-sm-7 contact-form wow fadeInLeft">
                            <h3>Deixa a que a sua opinião </h3>
	                    <p>
	                    	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. 
	                    	Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper <a href="">suscipit lobortis</a> 
	                    	nisl ut aliquip ex ea commodo consequat.
	                    </p>
	                    <form role="form" action="assets/sendmail.php" method="post">
	                    	<div class="form-group">
                                    <label for="contact-name"><strong>Name</strong></label>
	                        	<input type="text" name="name" placeholder="Enter your name..." class="contact-name" id="contact-name">
	                        </div>
	                    	<div class="form-group">
	                    		<label for="contact-email"><strong>Email</strong></label>
	                        	<input type="text" name="email" placeholder="Enter your email..." class="contact-email" id="contact-email">
	                        </div>
	                        
	                        <div class="form-group">
	                        	<label for="contact-message">Menssagem</label>
	                        	<textarea name="message" placeholder="A sua menssagem de coragem..." class="contact-message" id="contact-message"></textarea>
	                        </div>
	                        <button type="submit" class="btn">Send</button>
	                    </form>
	                </div>
	                
	            </div>
	        </div>
        </div>
        
        <!-- Meet Our Team -->
        <div class="team-container">
        	<div class="container">
	            <div class="row">
		            <div class="col-sm-12 team-title wow fadeIn">
		                <h2>A Equipa  </h2>
		            </div>
	            </div>
	            <div class="row">	            	
	            	<div class="col-sm-3">
		                
	                </div>
	                <div class="col-sm-3">
		                <div class="team-box wow fadeInDown">
		                    <img src="././Publica/assets/img/team/2.jpg" alt="" data-at2x="././Publica/assets/img/team/2.jpg">
		                    <h3>Jane Doe</h3>
		                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
		                    <div class="team-social">		                        
		                        <a href="#"><i class="fa fa-facebook"></i></a>
		                        <a href="#"><i class="fa fa-twitter"></i></a>
		                        <a href="#"><i class="fa fa-linkedin"></i></a>
		                        <a href="#"><i class="fa fa-envelope"></i></a>
		                    </div>
		                </div>
	                </div>
	                <div class="col-sm-3">
		                <div class="team-box wow fadeInUp">
		                    <img src="././Publica/assets/img/team/3.jpg" alt="" data-at2x="././Publica/assets/img/team/3.jpg">
		                    <h3>Tim Brown</h3>
		                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
		                    <div class="team-social">		                        
		                        <a href="#"><i class="fa fa-facebook"></i></a>
		                        <a href="#"><i class="fa fa-twitter"></i></a>
		                        <a href="#"><i class="fa fa-linkedin"></i></a>
		                        <a href="#"><i class="fa fa-envelope"></i></a>
		                    </div>
		                </div>
	                </div>
	                <div class="col-sm-3">
		                
	                </div>
	            </div>
	        </div>
        </div>

        <!-- Testimonials -->
        

        <!-- Footer -->
        <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-3 footer-box wow fadeInUp">
                    <h4>Sobre-nos</h4>
                    <div class="footer-box-text">
                        <p>
                            somos uma empresa de informação a tempo e hora basta.. tudo que vc precisa a que voce encontra
                        </p>
                        <p><a href="quemsomos">saiba mais...</a></p>
                    </div>
                </div>
                

                 <div class="col-sm-3 footer-box wow fadeInDown">
                    <h4>Contato</h4>
                    <div class="footer-box-text footer-box-text-contact">
                        <p><i class="fa fa-map-marker"></i> Address: avenida patriota BºBemvindo</p>
                        <p><i class="fa fa-phone"></i> Phone: 924-18-65-05/990-18-65-05</p>
                        <p><i class="fa fa-user"></i> Skype: Multimidia-web</p>
                        <p><i class="fa fa-envelope"></i> Email: <a href="">multimidia_web@gmail.com</a></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 wow fadeIn">
                    <div class="footer-border"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 footer-copyright wow fadeIn">
                    <p>Copyright 2012-todo direito reservado by <a href="">Multimidia-web</a>.</p>
                </div>
                <div class="col-sm-5 footer-social wow fadeIn">
                    <a href="almeida almeida"><i class="fa fa-facebook"></i></a>

                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-pinterest"></i></a>
                </div>
            </div>
        </div>
    </footer>
        
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

