
 <!-- Top menu -->
		<nav class="navbar" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="index.html">Andia - a super cool design agency...</a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="top-navbar-1">
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="index"   data-delay="1000">
								<i class="fa fa-home"></i><br>Home 
							</a>

						</li>
                                                  <li>
                                                    <a href="<?php echo APP_SITE_HOME;?>universidade"><i class="fa fa-tasks"></i><br>Universidades de Angola</a>
                                                  </li>
                                                
						<li class="active">
							<a href="<?php echo APP_SITE_HOME;?>servico"><i class="fa fa-camera"></i><br>Serviço</a>
						</li>
						<li >
							<a href="<?php echo APP_SITE_HOME;?>cursos"><i class="fa fa-tasks"></i><br>Cursos</a>
						</li>
						<li>
							<a href="<?php echo APP_SITE_HOME;?>quemSomos"><i class="fa fa-user"></i><br>Quem Somos</a>
						</li>
<!--						<li>
							<a href="contact.html"><i class="fa fa-envelope"></i><br>Contacto</a>
						</li>-->
						<li class="dropdown">
							<a href=" <?php echo APP_LOGIN;?>login"  data-hover="dropdown" data-delay="1000">
								<i class="fa fa-paperclip"></i><br>Login 
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

        <!-- Page Title -->
        <div class="page-title-container">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 wow fadeIn ">
                        <i class="fa fa-tasks"></i>
                        <h1>Serviços/</h1>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Services Full Width Text -->
        <div class="services-full-width-container">
        	<div class="container">
	            <div class="row">
	                <div class="col-sm-12 services-full-width-text wow fadeInLeft">
	                    <h3>FEIRA DE TECNOLOGIA DA UNIVERSIDADE INDEPENDENTE DE ANGOLA</h3>
	                    <p>
	                    	Depois da Cerimónia de Abertura pelo Vice-Reitor para a Área Académica, Prof. Doutor José António Fazenda, entrou-se no primeiro Painel, dedicado ao tema “O Perfil do Engenheiro no contexto do desenvolvimento Tecnológico de Angola”. Outro alto quadro da UnIA, o Vice-Reitor para Área Científica e Extensão Universitária, Professor Mestre Francisco César Almeida, dissertou sobre “Desafios no Ensino Superior a Médio Prazo, na perspectiva do Plano Nacional de Formação de Quadros”, numa comunicação que foi avidamente seguida por um Auditório Nobre completamente cheio e mereceu o interesse dos grandes órgãos de Comunicação Social presentes, com entrevistas imediatamente após, pela TPA e ANGOP, após o que o Centro Tecnológico Nacional do Ministério das Ciências e Tecnologia apresentou a sua posição sobre “Investigação vs Inovação”.
	                	</p>
	                </div>
	            </div>
	        </div>
        </div>

        <!-- Services -->
        <div class="services-container">
	        <div class="container">
	            <div class="row">
	            	<div class="col-sm-3">
		                <div class="service wow fadeInUp">
		                    <div class="service-icon"><i class="fa fa-hotel"></i></div>
		                    <h3>Unia</h3>
		                    <p>O ensino é um dos alicerces mais importantes um desenvolvimento sócio-económico sustentável de cada nação. Pelo que é indiscutível a importância da educação.....</p>
		                </div>
					</div>
					<div class="col-sm-3">
		                <div class="service wow fadeInDown">
		                    <div class="service-icon"><i class="fa fa-table"></i></div>
		                    <h3>Formação</h3>
		                    <p>“A revitalização do sector Industrial de Angola”. Falaram o Presidente da Associação Industrial de Angola (AIA), José Severino, sobre “Estratégias para materialização do sector industrial de Angola”..</p>
		                </div>
	                </div>
	                <div class="col-sm-3">
		                <div class="service wow fadeInUp">
		                    <div class="service-icon"><i class="fa fa-photo"></i></div>
		                    <h3>Galeria</h3>
		                    <p>sistemas de atendimento online, popularizaram-se muito nos últimos anos, por seus inúmeros benefícios, sendo principalmente citada a rapidez com que o usuário pode obter solução para o problema, como a maior vantagem apontada pelos usuários..</p>
		                </div>
	                </div>
	                <div class="col-sm-3">
		                <div class="service wow fadeInDown">
		                    <div class="service-icon"><i class="fa fa-print"></i></div>
		                    <h3>Livro didatico</h3>
		                    <p> No último dia realizou-se uma Oficina de Electrónica Digital/Analógica.

                                 A Feira de Tecnologia da UnIA (FETEC), agora prometida como evento anual, passa desde já a perfilar-se como mais um ex-libris de uma Universidade que tem 
	                    ..</p>
		                </div>
	                </div>
	            </div>
	        </div>
        </div>

        <!-- Services Half Width Text -->
        <div class="services-half-width-container">
        	<div class="container">
	            <div class="row">
	                <div class="col-sm-6 services-half-width-text wow fadeInLeft">
	                    <h3>A revitalização do sector Industrial de Angola</h3>
	                    <p>
	                    	O segundo Painel teve enfoque sobre “A revitalização do sector Industrial de Angola”. Falaram o Presidente da Associação Industrial de Angola (AIA), José Severino, sobre “Estratégias para materialização do sector industrial de Angola” e o Eng. Carlos Hernany Wilson de Carvalho, da SIIND, sobre “O contributo da ZEE para a diversificação da economia de Angola”

                              No dia dedicado a Exposições de empresas e entidades convidadas, houve também exposições de trabalhos dos estudantes da UnIA, a que se juntaram trabalhos dos estudantes da UTANGA, da Universidade Jean Piaget e do Instituto Superior Metropolitano de Angola.

                                Foi um dia memorável, com uma afluência que surpreendeu os próprios organizadores, um espaço onde deixou de existir espaço, tanta gente compareceu para visitar esta FETEC.

                                   </p>
	                </div>
	                <div class="col-sm-6 services-half-width-text wow fadeInUp">
	                    <h3>ÊXITO ABSOLUTO</h3>
	                    <p>
	                    	O Painel seguinte foi sobre “Os grandes desafios da Electrificação em Angola”, com apresentação pelo Prof.Eng. João de Sousa Barradas, da RNT – Rede Nacional de Transporte. O Dr. Fernando Koch e o Eng. Marco Brandão, da Biocom, falaram sobre “Energias Renováveis como alternativa do fornecimento da energia em Angola”.

                                 O segundo dia começou com uma manhã inteiramente dedicada às Novas Tecnologias. O Eng. Fernando Barreiro, da UnIA, explicou tudo sobre “4ª Geração – Tráfego Móvel” e o Eng. Cipriano Siquito, da Omnidata, falou sobre a “Importância do armazenamento da informação em ambientes Clássicos e virtuais na actualidade”. A Nova Base enviou o Dr. Cláudio Osório, que falou sobre “Produção de conteúdo digital em Angola para a massificação do e-learning” e a Movicel apresentou as “Principais diferenças entre LTE R8 e R10”, pelo Eng. Adriano Trindade. <strong>eiusmod tempor</strong> incididunt.
	                    </p>
	                </div>
	            </div>
	        </div>
        </div>

        
        <!-- Footer -->
        <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-3 footer-box wow fadeInUp">
                    <h4>Sobre-nos</h4>
                    <div class="footer-box-text">
                        <p>
                            somos uma empresa de informação a tempo e hora basta.. tudo que vc precisa a que voce encontra
                        </p>
                        <p><a href="quemsomos">saiba mais...</a></p>
                    </div>
                </div>
                

                <div class="col-sm-3 footer-box wow fadeInDown">
                    <h4>Contato</h4>
                    <div class="footer-box-text footer-box-text-contact">
                        <p><i class="fa fa-map-marker"></i> Address: avenida patriota BºBemvindo</p>
                        <p><i class="fa fa-phone"></i> Phone: 924-18-65-05/990-18-65-05</p>
                        <p><i class="fa fa-user"></i> Skype: Multimidia-web</p>
                        <p><i class="fa fa-envelope"></i> Email: <a href="">multimidia_web@gmail.com</a></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 wow fadeIn">
                    <div class="footer-border"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 footer-copyright wow fadeIn">
                    <p>Copyright 2012-todo direito reservado by <a href="">Multimidia-web</a>.</p>
                </div>
                <div class="col-sm-5 footer-social wow fadeIn">
                    <a href="almeida almeida"><i class="fa fa-facebook"></i></a>

                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-pinterest"></i></a>
                </div>
            </div>
        </div>
    </footer>

   

<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

