
<nav class="navbar" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="">Andia - a super cool design agency...</a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="top-navbar-1">
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="<?php echo APP_SITE_HOME;?>index"   data-delay="1000">
								<i class="fa fa-home"></i><br>Home 
							</a>
<!--							<ul class="dropdown-menu dropdown-menu-left" role="menu">
								<li><a href="index.html">Home</a></li>
								<li><a href="index-2.html">Home 2</a></li>
							</ul>-->
						</li>
                                                  <li class="active">
                                                    <a href="#"><i class="fa fa-tasks"></i><br>Universidades de Angola</a>
                                                  </li>
                                                
						<li >
							<a href="<?php echo APP_SITE_HOME;?>servico"><i class="fa fa-camera"></i><br>Serviço</a>
						</li>
						<li >
							<a href="<?php echo APP_SITE_HOME;?>cursos"><i class="fa fa-tasks"></i><br>Cursos</a>
						</li>
						<li>
							<a href="<?php echo APP_SITE_HOME;?>quemSomos"><i class="fa fa-user"></i><br>Quem Somos</a>
						</li>
<!--						<li>
							<a href="contact.html"><i class="fa fa-envelope"></i><br>Contacto</a>
						</li>-->
						<li class="dropdown">
							<a href="<?php echo APP_LOGIN;?>login"  data-hover="dropdown" data-delay="1000">
								<i class="fa fa-paperclip"></i><br>Login 
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

        <!-- Page Title -->
        <div class="page-title-container">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 wow fadeIn">
                        <i class="fa fa-tasks"></i>
                        <h1>Universidades De Angola/</h1>
                        <p>A forma&ccedil;&atilde;o da Na&ccedil;&atilde;o</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Services Full Width Text -->
        <div class="services-full-width-container">
        	<div class="container">
	            <div class="row">
	                <div class="col-sm-12 services-full-width-text wow fadeInLeft">
	                    <h3> A que voce encontra a sua universidade</h3>
	                    <p>
	                    	Sendo a UnIA uma Universidade angolana achou-se por bem arrancar com o Ano Propedêutico por se julgar útil e necessário para moldar os conhecimentos dos alunos que ingressaram no ensino superior, alguns deles após largos anos ausentes do sistema de ensino devido aos de Guerra e instabilidade que o país viveu no passado.

Além do que, as proveniências são várias e os graus de formação do ensino secundário ou outros eventuais cursos médios também eram e continuam a ser muito diferentes entre os alunos.
	                	</p>
	                </div>
	            </div>
	        </div>
        </div>

<!--   primeiro bloco     
        -->
        
        <div class="work-container">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 work-title wow fadeIn">
                    <h2> O saber dos povos</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <div class="work wow fadeInUp">
                        <img src="././Publica/assets/img/portfolio/work1.jpg" alt="Lorem Website" data-at2x="assets/img/portfolio/work1.jpg">
                        <h3> U.N.I.A</h3>
                        <p></p>
                        <div class="work-bottom">
                          
                            <a class="big-link-2" href="http://www.unia.ao/"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInDown">
                        <img src="././Publica/assets/img/portfolio/work2.jpg" alt="Ipsum Logo" data-at2x="assets/img/portfolio/work2.jpg">
                        <h3> U.A.N</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
                        <div class="work-bottom">
                           
                            <a class="big-link-2" href="http://www.uan.ao/"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInUp">
                        <img src="././Publica/assets/img/portfolio/work3.jpg" alt="Dolor Prints" data-at2x="assets/img/portfolio/work3.jpg">
                        <h3>U.M.P.A</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
                        <div class="work-bottom">
                          
                            <a class="big-link-2" href="#?"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInDown">
                        <img src="././Publica/assets/img/portfolio/work4.jpg" alt="Sit Amet Website" data-at2x="assets/img/portfolio/work4.jpg">
                        <h3> U.G.S </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
                        <div class="work-bottom">
                           
                            <a class="big-link-2" href=""><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        
        
        
        
        <!-- segundo bloco -->
        <div class="work-container">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 work-title wow fadeIn">
                    <h2> </h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <div class="work wow fadeInUp">
                        <img src="././Publica/assets/img/portfolio/work1.jpg" alt="Lorem Website" data-at2x="assets/img/portfolio/work1.jpg">
                        <h3>U.T.A</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
                        <div class="work-bottom">
                            
                            <a class="big-link-2" href=""><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInDown">
                        <img src="././Publica/assets/img/portfolio/work2.jpg" alt="Ipsum Logo" data-at2x="assets/img/portfolio/work2.jpg">
                        <h3>I.U.P.A</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
                        <div class="work-bottom">
                           
                            <a class="big-link-2" href=""><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInUp">
                        <img src="././Publica/assets/img/portfolio/work3.jpg" alt="Dolor Prints" data-at2x="assets/img/portfolio/work3.jpg">
                        <h3>PIAJE</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
                        <div class="work-bottom">
                           
                            <a class="big-link-2" href=""><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInDown">
                        <img src="././Publica/assets/img/portfolio/work4.jpg" alt="Sit Amet Website" data-at2x="assets/img/portfolio/work4.jpg">
                        <h3> U.S.T.A  </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
                        <div class="work-bottom">
                          
                            <a class="big-link-2" href=""><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        <!-- terceiro bloco -->
        <div class="work-container">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 work-title wow fadeIn">
                    <h2> </h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <div class="work wow fadeInUp">
                        <img src="././Publica/assets/img/portfolio/work1.jpg" alt="Lorem Website" data-at2x="assets/img/portfolio/work1.jpg">
                        <h3>U.F.A.</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
                        <div class="work-bottom">
                           
                            <a class="big-link-2" href=""><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInDown">
                        <img src="././Publica/assets/img/portfolio/work2.jpg" alt="Ipsum Logo" data-at2x="assets/img/portfolio/work2.jpg">
                        <h3>u.Katanga.A</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
                        <div class="work-bottom">
                            
                            <a class="big-link-2" href=""><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInUp">
                        <img src="././Publica/assets/img/portfolio/work3.jpg" alt="Dolor Prints" data-at2x="assets/img/portfolio/work3.jpg">
                        <h3>U.jose Dos Santos.A</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
                        <div class="work-bottom">
                          
                            <a class="big-link-2" href=""><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="work wow fadeInDown">
                        <img src="././Publica/assets/img/portfolio/work4.jpg" alt="Sit Amet Website" data-at2x="assets/img/portfolio/work4.jpg">
                        <h3> U.Mandume.A  </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
                        <div class="work-bottom">
                          
                            <a class="big-link-2" href=""><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


        <!-- Footer -->
        <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-3 footer-box wow fadeInUp">
                    <h4>Sobre-nos</h4>
                    <div class="footer-box-text">
                        <p>
                            somos uma empresa de informação a tempo e hora basta.. tudo que vc precisa a que voce encontra
                        </p>
                        <p><a href="about.html">saiba mais...</a></p>
                    </div>
                </div>
                

                <div class="col-sm-3 footer-box wow fadeInDown">
                    <h4>Contato</h4>
                    <div class="footer-box-text footer-box-text-contact">
                        <p><i class="fa fa-map-marker"></i> Address: avenida patriota BºBemvindo</p>
                        <p><i class="fa fa-phone"></i> Phone: 924-18-65-05/990-18-65-05</p>
                        <p><i class="fa fa-user"></i> Skype: Multimidia-web</p>
                        <p><i class="fa fa-envelope"></i> Email: <a href="">multimidia_web@gmail.com</a></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 wow fadeIn">
                    <div class="footer-border"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 footer-copyright wow fadeIn">
                    <p>Copyright 2012-todo direito reservado by <a href="">Multimidia-web</a>.</p>
                </div>
                <div class="col-sm-5 footer-social wow fadeIn">
                    <a href="almeida almeida"><i class="fa fa-facebook"></i></a>

                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-pinterest"></i></a>
                </div>
            </div>
        </div>
    </footer>
        
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

